---
version: "2"
services:
  bookstack:
    image: ghcr.io/linuxserver/bookstack
    # ports: 8080:80
    environment:
      - PUID=1000
      - PGID=1000
      # - APP_URL=FILL IN
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=DEFINE
      - DB_DATABASE=bookstackapp
    volumes:
      - ./app/config:/config
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: ghcr.io/linuxserver/mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=DEFINE
      - TZ=Europe/London
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=DEFINE
    volumes:
      - ./db/config:/config
    restart: unless-stopped
